# Dockerfile for DDNSTO based alpine
# Copyright (C) 2020 - 2020 Janson <janson@linkease.com>
# Reference URL:
# https://www.ddnsto.com/

FROM --platform=${TARGETPLATFORM} alpine:latest
LABEL maintainer="Janson <janson@linkease.com>"

ARG TARGETPLATFORM
COPY ddnsto-dl.sh /root/ddnsto-dl.sh
RUN set -ex \
	&& chmod +x /root/ddnsto-dl.sh \
	&& /root/ddnsto-dl.sh "${TARGETPLATFORM}"

ENV TZ=Asia/Shanghai
ENV TOKEN=
ENV DEVICE_IDX=0
ENV LOG_LEVEL=2

CMD [ "/usr/bin/ddnsto-monitor.sh"]
